#!/usr/bin/env php
<?php
/**
 * Chatter: Twitter command line client file
 *
 * @package Chatter
 * @author Jansen Price <jansen.price@gmail.com>
 * @license http://www.opensource.org/licenses/mit-license.php MIT
 * @version 2.4.0 (2012-08-18)
 */

date_default_timezone_set('America/Chicago');

$root = realpath(dirname(__FILE__));

if (!file_exists($root . DIRECTORY_SEPARATOR . 'vendor/autoload.php')) {
    die("You must run `composer install` before proceeding\n");
}

$loader = require_once $root . DIRECTORY_SEPARATOR . 'vendor/autoload.php';
$loader->add('', $root . DIRECTORY_SEPARATOR . 'src');

$chatter = new ChatterTerminal\Client($argv);
