#!/usr/bin/env php
<?php
/**
 * Chatter: Twitter command line client file
 *
 * @package Chatter
 * @author Jansen Price <jansen.price@gmail.com>
 * @license http://www.opensource.org/licenses/mit-license.php MIT
 * @version 2.4.0 (2012-08-18)
 */

date_default_timezone_set('America/Chicago');

$loader = require_once 'vendor/autoload.php';
$loader->add('', 'src');

require_once 'lib/twitteroauth/twitteroauth.php';

$chatter = new \ChatterTerminal\Client($argv);
